# Site settings
title: 吕彦俊的技术博客
email: yanjun.lu27@icould.com
description: > #吕彦俊的技术博客
baseurl: "http://wrinkleman.top" # the subpath of your site, e.g. /blog/
url: "http://wrinkleman.top" # the base hostname & protocol for your site
# twitter_username: coolnameismy@hotmail.com
github_username:  wrinkleman

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 吕彦俊
  email: yanjun.lu27@icloud.com
  link: http://wrinkleman.top/
  # weibo: http://weibo.com/1897719834
  github: http://github.com/wrinkleman
title: 路易的技术博客                             #自定义常量

# avatar头像及Favicon
avatar: https://avatars0.githubusercontent.com/u/18319813?v=3&u=1d112ca1f60caf55d290d41a1a0b96ed685f8cba&s=140
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:
  src: //hm.baidu.com/hm.js?22d94317cfb9f9e0bb476228d9f79278

# disqus 设置
disqus:
  shortname: louis